version: '2.0'
services:
    test-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: test-api
        ports:
            - '80:80'
        volumes:
            - .:/var/www/html
        command: /bin/bash /var/www/html/docker/test-api.sh
